name: Run Laravel Tests

on:
  push: # <-- runs on all pushes to any branch
  pull_request: # still includes pull request events

jobs:
  laravel-tests:
    name: Laravel Tests (PHPStan, Pint, PHPUnit)
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testing
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, bcmath, pdo_mysql
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Clear and cache config
        run: |
          php artisan config:clear
          php artisan config:cache

      - name: Run migrations
        run: php artisan migrate --force

      - name: Optimize Laravel
        run: php artisan optimize

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyse

      - name: Run Laravel Pint
        run: ./vendor/bin/pint --test

      - name: Run PHPUnit
        env:
          DB_CONNECTION: sqlite
        run: ./vendor/bin/pest
